const teamAbbrev: Record<string, string> = {
  Diamondbacks: "ARI",
  Braves: "ATL",
  Orioles: "BAL",
  "Red Sox": "BOS",
  Cubs: "CHC",
  "White Sox": "CWS",
  Reds: "CIN",
  Guardians: "CLE",
  Rockies: "COL",
  Tigers: "DET",
  Astros: "HOU",
  Royals: "KC",
  Angels: "LAA",
  Dodgers: "LAD",
  Marlins: "MIA",
  Brewers: "MIL",
  Twins: "MIN",
  Mets: "NYM",
  Yankees: "NYY",
  Athletics: "ATH",
  Phillies: "PHI",
  Pirates: "PIT",
  Padres: "SDP",
  Giants: "SFG",
  Mariners: "SEA",
  Cardinals: "STL",
  Rays: "TB",
  Rangers: "TEX",
  "Blue Jays": "TOR",
  Nationals: "WSN",
};

export default teamAbbrev;
